server:
  port: 8089
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: max
    password: 
  jpa:
    hibernate: 
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
    temp: 
      use_jdbc_metadata_defaults: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  activemq:
    in-memory: false
    broker-url: tcp://activemq:61616
  jms:
    pub-sub-domain: true

