server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: userdb
    password: password

  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
