server:
  port: 8089
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: max
    password: 

  jpa:
    hibernate: 
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
    temp: 
      use_jdbc_metadata_defaults: false
